url: https://mfurquim.github.io
baseurl: ""

# Site settings
title: MFurquim Dev
email: mateus@mfurquim.dev
description: "Engenheiro de software e entusiasta linux. Aprendizados diários de um progamador."


# Team names, titles and social links
people:
- name: Mateus Furquim
  pic: 1
  position: Machine Learning Engineer
  social:
    - title: twitter
      url: https://twitter.com/mfurquimdev
    - title: linkedin
      url: https://www.linkedin.com/in/mmfurquim/
    - title: instagram
      url: https://www.instagram.com/mfurquimdev


# # Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
